"""The DCU results report is what the table renders, not a second hand-written source.

The gap this closes, measured: the report lived outside the repository as a hand-written
markdown file for two days. In that time F-2026-09-18-002 corrected its floor count twice
and then withdrew its whole argument from bytes -- and the report kept the first count and
the withdrawn argument, because nothing connected the two. A reader with the report and no
ledger would have believed all of it.

The report is now generated by `tools/render_dcu_report.py` from the retained medians. This
asserts the committed file is that rendering, so a table change that is not reflected in the
report fails here rather than being discovered by a reader.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "tools/render_dcu_report.py"
REPORT = ROOT / "docs/dcu-gfx938-results.md"
DATA = ROOT / "findings/data/2026-09-18-dcu-confirmatory-medians.json"


class TheRenderedReport(unittest.TestCase):
    def setUp(self) -> None:
        self.data = json.loads(DATA.read_text(encoding="utf-8"))

    def test_the_committed_report_is_what_the_tool_renders(self) -> None:
        result = subprocess.run([sys.executable, str(TOOL), "--check"],
                                cwd=ROOT, capture_output=True, text=True)
        self.assertEqual(result.returncode, 0,
                         f"{result.stdout}{result.stderr}\n"
                         "Re-run tools/render_dcu_report.py --write")

    def test_the_report_states_the_counts_the_table_gives(self) -> None:
        """Belt and braces: --check compares whole files, so it would also pass if the tool
        and the table drifted together. These read the numbers out of the rendered text."""
        text = REPORT.read_text(encoding="utf-8")
        rows, floor = self.data["medians_ms"], self.data["floor_ms"]
        at_floor = sum(1 for r in rows.values()
                       if r["candidate"] == floor and r["baseline"] == floor)
        self.assertIn(f"**{at_floor} tasks report exactly {floor} ms", text)
        self.assertIn(f"**{len(rows)} of 29 tasks", text)
        self.assertIn(f"**{self.data['timer_quantum_ns']} ns**", text)

    def test_the_withdrawn_argument_is_marked_withdrawn_and_not_asserted(self) -> None:
        """The specific sentences the report carried while they were already retracted."""
        text = REPORT.read_text(encoding="utf-8")
        # Block-quote markers are dropped before flattening: the retraction lives inside a
        # "> " quote, so a wrapped phrase otherwise reads as "sit in the > flat region".
        flat = " ".join(line.lstrip("> ") for line in text.splitlines()).replace("  ", " ")
        flat = " ".join(flat.split())
        for retracted in ("Eleven tasks report", "**The task shapes sit in the flat region**",
                          "is what a quantized timer does",
                          "The reason is the timer, not"):
            self.assertNotIn(retracted, text)
        self.assertIn("That argument is withdrawn", text)
        # Two claims were withdrawn here, not one: the bytes argument, and the
        # quantization account written in its place. The second was asserted the same way
        # the first was, and a report that names only the first reads as though the
        # replacement had been established.
        self.assertIn("withdrawn too", flat)
        self.assertIn("uniform quantization does not in general collapse", flat.lower())
        # It may quote the retracted claim while retracting it, but only inside the block
        # quote that does the retracting.
        for sentence in ("bandwidth-bound work cannot do that",
                         'sit in the flat region"'):
            self.assertIn(sentence, flat, "the retraction no longer names what it retracts")

    def test_the_report_defers_to_the_ledger(self) -> None:
        # Normalised, because the prose is wrapped and a phrase can straddle a newline.
        text = " ".join(REPORT.read_text(encoding="utf-8").split())
        self.assertIn("the record wins", text)
        self.assertIn("tools/render_dcu_report.py", text)


if __name__ == "__main__":
    unittest.main()
