"""Research Lab public Interface."""

from .checkpoints import CheckpointObservation, TurnObservation, project_checkpoints
from .compose import (
    broker_execution_sha256,
    execute_matched_from_config,
    execute_portfolio_from_config,
)
from .core import (
    AnalysisInclusion,
    CampaignLock,
    CampaignRef,
    ClaimView,
    Lab,
    PortfolioAssay,
    PortfolioStudyReport,
    RunEvaluator,
    RunProvider,
    StudyContract,
    StudyReport,
    TurnRequest,
    matched_evidence_policy_v1,
    scientific_matched_analysis_plan_v2,
)
from .environments import (
    AuthoringEnvironment,
    BuildRequest,
    CandidateSubmission,
    DirectCudaEnvironment,
    EnvironmentResult,
    NvccToolchainBuilder,
    OpenCakeEnvironment,
    ToolchainBuilder,
    TritonToolchainBuilder,
)
from .executor import ExecutorRevision
from .faults import CandidateCompileRejected, RunProtocolFault
from .portfolio import ExactShape, KernelSeed, SpecialistLowering, lower_specialists
from .providers import (
    CANDIDATE_SET_ENVELOPE_V1,
    CODEX_DISABLED_FEATURES,
    CodexInvocationBuilder,
    CodexProviderAdapter,
    CodexRunProvider,
    ProviderAuxiliaryActivity,
    ProviderInvocation,
    ProviderQualificationReceipt,
    ProviderTurn,
    normalize_codex_turn,
    required_live_provider_qualification_scope,
)
from .qsa_feedback import (
    qsa_compiler_feedback,
    qsa_evaluation_feedback,
    qsa_next_turn_request,
)
from .runtime import BoundedBrokerEvaluator, BrokerSubmitter, CommandBrokerSubmitter

__all__ = [
    "AnalysisInclusion",
    "CampaignLock",
    "CampaignRef",
    "ClaimView",
    "CheckpointObservation",
    "Lab",
    "PortfolioAssay",
    "PortfolioStudyReport",
    "RunEvaluator",
    "RunProvider",
    "StudyContract",
    "StudyReport",
    "TurnRequest",
    "TurnObservation",
    "project_checkpoints",
    "matched_evidence_policy_v1",
    "scientific_matched_analysis_plan_v2",
    "AuthoringEnvironment",
    "BuildRequest",
    "CandidateSubmission",
    "DirectCudaEnvironment",
    "EnvironmentResult",
    "ExecutorRevision",
    "NvccToolchainBuilder",
    "OpenCakeEnvironment",
    "TritonToolchainBuilder",
    "ToolchainBuilder",
    "CodexInvocationBuilder",
    "CANDIDATE_SET_ENVELOPE_V1",
    "CODEX_DISABLED_FEATURES",
    "CodexProviderAdapter",
    "CodexRunProvider",
    "ProviderAuxiliaryActivity",
    "ProviderInvocation",
    "ProviderQualificationReceipt",
    "ProviderTurn",
    "normalize_codex_turn",
    "required_live_provider_qualification_scope",
    "qsa_compiler_feedback",
    "qsa_evaluation_feedback",
    "qsa_next_turn_request",
    "ExactShape",
    "KernelSeed",
    "SpecialistLowering",
    "lower_specialists",
    "BoundedBrokerEvaluator",
    "BrokerSubmitter",
    "CommandBrokerSubmitter",
    "execute_matched_from_config",
    "execute_portfolio_from_config",
    "broker_execution_sha256",
    "RunProtocolFault",
    "CandidateCompileRejected",
]
