// Generated by Open-Cake native ranked-mailbox lowering.
// Math and queue effects are independently admitted before template binding.
#include <cuda.h>
#include <cuda_runtime.h>
#include <cuda_bf16.h>
@CHUNK_MATH@
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <cmath>

@INLINE_MATH@
namespace {
constexpr int R = @RANKS@;
#ifndef CAKE_WEAVE_TOKENS
#define CAKE_WEAVE_TOKENS @TOKENS@
#endif
constexpr int T = CAKE_WEAVE_TOKENS;
static_assert(T == 7 || T == 8, "development Workload admits T=7 or T=8 only");
constexpr int K = @ROUTES@;
constexpr int E = @EXPERTS@;
constexpr int H = @HIDDEN@;
constexpr int I = @INTERMEDIATE@;
constexpr int TASK_CAP = R * T * K;
constexpr int PAYLOAD_CAP = (R - 1) * T;
constexpr int SMS = @SMS@;

struct Mailbox {
    int payload_tail, task_tail, task_head, dispatch_sources_done, dispatch_cursor;
    int dispatch_completed, comm_done, combine_cursor, steal_permits;
    int stolen, compute_completed, status;
    int payload_ready[PAYLOAD_CAP];
    __nv_bfloat16 payload[PAYLOAD_CAP * H];
    int task_ready[TASK_CAP];
    int source[TASK_CAP], token[TASK_CAP], route_slot[TASK_CAP], expert[TASK_CAP];
    int payload_slot[TASK_CAP];
    float contributions[T * K * H];
    int contribution_ready[T * K];
    int chunk_completed[T];
    __nv_bfloat16 output[T * H];
};

struct Params {
    Mailbox* mailboxes[R];
    const __nv_bfloat16* hidden;
    const int* expert_ids;
    const float* route_weights;
    const __nv_bfloat16* w_up_gate;
    const __nv_bfloat16* w_down;
    int rank, comm_ctas, chunks, steal_budget;
    int source_chunks[R];
};

__device__ __forceinline__ int sys_add_relaxed(int* pointer, int value) {
    int old;
    asm volatile("atom.relaxed.sys.global.add.s32 %0, [%1], %2;"
                 : "=r"(old)
                 : "l"(reinterpret_cast<unsigned long long>(pointer)), "r"(value)
                 : "memory");
    return old;
}

__device__ __forceinline__ int sys_add_acq_rel(int* pointer, int value) {
    int old;
    asm volatile("atom.acq_rel.sys.global.add.s32 %0, [%1], %2;"
                 : "=r"(old)
                 : "l"(reinterpret_cast<unsigned long long>(pointer)), "r"(value)
                 : "memory");
    return old;
}

__device__ __forceinline__ int sys_add_release(int* pointer, int value) {
    int old;
    asm volatile("atom.release.sys.global.add.s32 %0, [%1], %2;"
                 : "=r"(old)
                 : "l"(reinterpret_cast<unsigned long long>(pointer)), "r"(value)
                 : "memory");
    return old;
}

__device__ __forceinline__ int sys_load_acquire(const int* pointer) {
    int value;
    asm volatile("ld.acquire.sys.global.s32 %0, [%1];"
                 : "=r"(value)
                 : "l"(reinterpret_cast<unsigned long long>(pointer))
                 : "memory");
    return value;
}

__device__ __forceinline__ int flag_load_acquire(const int* pointer) {
    return sys_load_acquire(pointer);
}

__device__ __forceinline__ void flag_publish(int* pointer) {
    asm volatile("st.release.sys.global.s32 [%0], %1;" ::
                 "l"(reinterpret_cast<unsigned long long>(pointer)), "r"(1)
                 : "memory");
}

__device__ __forceinline__ int warp_claim(int* cursor, int lane) {
    int task = lane == 0 ? atomicAdd(cursor, 1) : 0;
    return __shfl_sync(0xffffffffu, task, 0);
}

__device__ __forceinline__ void dispatch_one(const Params* params, int token,
                                              int lane) {
    int destinations[K];
    int payload_slots[K];
    for (int route = 0; route < K; ++route) {
        const int expert = params->expert_ids[token * K + route];
        const int destination = expert / (E / R);
        Mailbox* remote = params->mailboxes[destination];
        int payload_slot = -1;
        if (destination != params->rank) {
            for (int prior = 0; prior < route; ++prior)
                if (destinations[prior] == destination)
                    payload_slot = payload_slots[prior];
            if (payload_slot < 0) {
                // CAKE_EFFECT: payload.reserve
                payload_slot = lane == 0 ? sys_add_relaxed(&remote->payload_tail, 1) : 0;
                payload_slot = __shfl_sync(0xffffffffu, payload_slot, 0);
                if (lane < H)
                    remote->payload[payload_slot * H + lane] =
                        params->hidden[token * H + lane];
                __syncwarp();
                // CAKE_EFFECT: payload.publish
                if (lane == 0) flag_publish(&remote->payload_ready[payload_slot]);
                __syncwarp();
            }
        }
        destinations[route] = destination;
        payload_slots[route] = payload_slot;
        // CAKE_EFFECT: task.reserve
        int task_slot = lane == 0 ? sys_add_relaxed(&remote->task_tail, 1) : 0;
        task_slot = __shfl_sync(0xffffffffu, task_slot, 0);
        if (lane == 0) {
            remote->source[task_slot] = params->rank;
            remote->token[task_slot] = token;
            remote->route_slot[task_slot] = route;
            remote->expert[task_slot] = expert;
            remote->payload_slot[task_slot] = payload_slot;
            // CAKE_EFFECT: task.publish
            flag_publish(&remote->task_ready[task_slot]);
        }
        __syncwarp();
    }
    if (lane == 0) {
        const int old = sys_add_acq_rel(
            &params->mailboxes[params->rank]->dispatch_completed, 1);
        if (old == T - 1)
            for (int peer = 0; peer < R; ++peer)
                sys_add_release(&params->mailboxes[peer]->dispatch_sources_done, 1);
    }
    __syncwarp();
}

__device__ __forceinline__ int try_claim(Mailbox* local) {
    while (true) {
        const int head = atomicAdd(&local->task_head, 0);
        const int tail = sys_load_acquire(&local->task_tail);
        if (head >= tail) return -1;
        // CAKE_EFFECT: task.claim
        if (atomicCAS(&local->task_head, head, head + 1) == head) return head;
    }
}

__device__ __forceinline__ bool no_more_inbound(Mailbox* local) {
    if (sys_load_acquire(&local->dispatch_sources_done) != R) return false;
    const int tail = sys_load_acquire(&local->task_tail);
    return atomicAdd(&local->task_head, 0) >= tail;
}

__device__ __forceinline__ void compute_one(const Params* params, int slot,
                                             int lane) {
    Mailbox* local = params->mailboxes[params->rank];
    // CAKE_EFFECT: task.acquire
    while (flag_load_acquire(&local->task_ready[slot]) == 0) __nanosleep(64);
    const int expert = local->expert[slot];
    const int local_expert = expert - params->rank * (E / R);
    const int source = local->source[slot];
    const int token = local->token[slot];
    const int route = local->route_slot[slot];
    const int payload_slot = local->payload_slot[slot];
    // CAKE_EFFECT: payload.acquire
    if (payload_slot >= 0)
        while (flag_load_acquire(&local->payload_ready[payload_slot]) == 0)
            __nanosleep(64);
    Mailbox* origin = params->mailboxes[source];
    const int contribution = token * K + route;
    __shared__ float activated[I];
    const __nv_bfloat16* hidden = payload_slot >= 0
        ? local->payload + payload_slot * H : params->hidden + token * H;
    @ENTRY@_expert(hidden, params->w_up_gate, params->w_down, local_expert,
                   activated, origin->contributions + contribution * H, lane);
    __syncthreads();
    if (lane == 0) {
        // CAKE_EFFECT: return.publish
        flag_publish(&origin->contribution_ready[contribution]);
        // CAKE_EFFECT: return.chunk_complete
        sys_add_relaxed(&origin->chunk_completed[
            cake_weave::chunk_for_token<T>(token, params->source_chunks[source])], 1);
        atomicAdd(&local->compute_completed, 1);
    }
    __syncthreads();
}

__device__ __forceinline__ void combine_one(const Params* params, int token,
                                             int lane) {
    Mailbox* local = params->mailboxes[params->rank];
    const int chunk = cake_weave::chunk_for_token<T>(token, params->chunks);
    // CAKE_EFFECT: return.acquire
    while (sys_load_acquire(&local->chunk_completed[chunk]) <
           cake_weave::chunk_size<T>(chunk, params->chunks) * K) __nanosleep(64);
    for (int route = 0; route < K; ++route)
        while (flag_load_acquire(&local->contribution_ready[token * K + route]) == 0)
            __nanosleep(64);
    @ENTRY@_combine(local->contributions, params->route_weights,
                    local->output, token, lane);
    __syncwarp();
}

__global__ void @ENTRY@_kernel(Params* params) {
    const int lane = int(threadIdx.x);
    Mailbox* local = params->mailboxes[params->rank];
    if (params->comm_ctas <= 0 || params->comm_ctas >= SMS ||
        params->chunks <= 0 || params->chunks > T ||
        params->steal_budget < 0 || params->steal_budget > TASK_CAP) {
        if (blockIdx.x == 0 && lane == 0) local->status = -1;
        return;
    }
    const bool communication = int(blockIdx.x) < params->comm_ctas;
    if (communication) {
        while (true) {
            const int token = warp_claim(&local->dispatch_cursor, lane);
            if (token >= T) break;
            dispatch_one(params, token, lane);
        }
        if (lane == 0)
            while (sys_load_acquire(&local->dispatch_completed) < T)
                __nanosleep(64);
        __syncwarp();
        while (true) {
            int stop = 0;
            int permit = 0;
            if (lane == 0) {
                stop = sys_load_acquire(&local->chunk_completed[0]) >=
                       cake_weave::chunk_size<T>(0, params->chunks) * K ||
                       atomicAdd(&local->stolen, 0) >= params->steal_budget ||
                       no_more_inbound(local);
                if (!stop) {
                    int used = atomicAdd(&local->steal_permits, 0);
                    while (used < params->steal_budget) {
                        const int observed = atomicCAS(&local->steal_permits,
                                                       used, used + 1);
                        if (observed == used) {
                            permit = 1;
                            break;
                        }
                        used = observed;
                    }
                }
            }
            stop = __shfl_sync(0xffffffffu, stop, 0);
            if (stop) break;
            permit = __shfl_sync(0xffffffffu, permit, 0);
            if (!permit) {
                __nanosleep(64);
                continue;
            }
            int slot = lane == 0 ? try_claim(local) : 0;
            slot = __shfl_sync(0xffffffffu, slot, 0);
            if (slot >= 0) {
                compute_one(params, slot, lane);
                if (lane == 0) atomicAdd(&local->stolen, 1);
            } else {
                // A temporary empty queue does not spend the steal budget.
                if (lane == 0) atomicSub(&local->steal_permits, 1);
                __nanosleep(64);
            }
        }
        if (lane == 0) atomicAdd(&local->comm_done, 1);
        __syncwarp();
    } else {
        while (true) {
            int slot = lane == 0 ? try_claim(local) : 0;
            slot = __shfl_sync(0xffffffffu, slot, 0);
            if (slot >= 0) {
                compute_one(params, slot, lane);
            } else if (no_more_inbound(local)) break;
            else __nanosleep(64);
        }
    }
    if (lane == 0)
        while (atomicAdd(&local->comm_done, 0) < params->comm_ctas)
            __nanosleep(64);
    __syncwarp();
    while (true) {
        const int token = warp_claim(&local->combine_cursor, lane);
        if (token >= T) break;
        combine_one(params, token, lane);
    }
}
}  // namespace

extern "C" size_t @ENTRY@_mailbox_bytes() { return sizeof(Mailbox); }
extern "C" int @ENTRY@_tokens() { return T; }
extern "C" size_t @ENTRY@_output_offset() { return offsetof(Mailbox, output); }
extern "C" size_t @ENTRY@_output_bytes() { return T * H * sizeof(__nv_bfloat16); }
extern "C" size_t @ENTRY@_status_offset() { return offsetof(Mailbox, status); }
extern "C" size_t @ENTRY@_payload_tail_offset() { return offsetof(Mailbox, payload_tail); }
extern "C" size_t @ENTRY@_task_tail_offset() { return offsetof(Mailbox, task_tail); }
extern "C" size_t @ENTRY@_steal_permits_offset() { return offsetof(Mailbox, steal_permits); }
extern "C" size_t @ENTRY@_stolen_offset() { return offsetof(Mailbox, stolen); }
extern "C" size_t @ENTRY@_compute_completed_offset() {
    return offsetof(Mailbox, compute_completed);
}
extern "C" size_t @ENTRY@_dispatch_done_offset() {
    return offsetof(Mailbox, dispatch_sources_done);
}

extern "C" int @ENTRY@_prepare_rank(int rank, void** mailboxes,
    const void* hidden, const void* expert_ids, const void* route_weights,
    const void* w_up_gate, const void* w_down,
    int comm_ctas, int chunks, int steal_budget,
    const int* source_chunks, void** result) {
    if (rank < 0 || rank >= R || !mailboxes || !hidden || !expert_ids ||
        !route_weights || !w_up_gate || !w_down || !source_chunks || !result)
        return int(cudaErrorInvalidValue);
    if (chunks < 1 || chunks > T || source_chunks[rank] != chunks ||
        comm_ctas < 1 || comm_ctas >= SMS ||
        steal_budget < 0 || steal_budget > TASK_CAP)
        return int(cudaErrorInvalidValue);
    int current_device = -1;
    cudaError_t error = cudaGetDevice(&current_device);
    if (error != cudaSuccess) return int(error);
    if (current_device != rank) return int(cudaErrorInvalidDevice);
    Params host{};
    for (int peer = 0; peer < R; ++peer) {
        if (!mailboxes[peer] || source_chunks[peer] < 1 || source_chunks[peer] > T)
            return int(cudaErrorInvalidValue);
        cudaPointerAttributes attributes{};
        error = cudaPointerGetAttributes(&attributes, mailboxes[peer]);
        if (error != cudaSuccess) return int(error);
        if (attributes.type != cudaMemoryTypeDevice || attributes.device != peer)
            return int(cudaErrorInvalidDevicePointer);
        host.mailboxes[peer] = static_cast<Mailbox*>(mailboxes[peer]);
        host.source_chunks[peer] = source_chunks[peer];
    }
    const void* local_inputs[] = {hidden, expert_ids, route_weights,
                                  w_up_gate, w_down};
    for (const void* input : local_inputs) {
        cudaPointerAttributes attributes{};
        error = cudaPointerGetAttributes(&attributes, input);
        if (error != cudaSuccess) return int(error);
        if (attributes.type != cudaMemoryTypeDevice || attributes.device != rank)
            return int(cudaErrorInvalidDevicePointer);
    }
    int host_ids[T * K];
    error = cudaMemcpy(host_ids, expert_ids, sizeof(host_ids), cudaMemcpyDeviceToHost);
    if (error != cudaSuccess) return int(error);
    float host_weights[T * K];
    error = cudaMemcpy(host_weights, route_weights, sizeof(host_weights),
                       cudaMemcpyDeviceToHost);
    if (error != cudaSuccess) return int(error);
    for (int item = 0; item < T; ++item) {
        float sum = 0.0f;
        for (int route = 0; route < K; ++route) {
            const int index = item * K + route;
            if (host_ids[index] < 0 || host_ids[index] >= E ||
                !std::isfinite(host_weights[index]) || host_weights[index] < 0.0f)
                return int(cudaErrorInvalidValue);
            for (int prior = 0; prior < route; ++prior)
                if (host_ids[item * K + prior] == host_ids[index])
                    return int(cudaErrorInvalidValue);
            sum += host_weights[index];
        }
        if (std::fabs(sum - 1.0f) > 1.0e-6f)
            return int(cudaErrorInvalidValue);
    }
    host.hidden = static_cast<const __nv_bfloat16*>(hidden);
    host.expert_ids = static_cast<const int*>(expert_ids);
    host.route_weights = static_cast<const float*>(route_weights);
    host.w_up_gate = static_cast<const __nv_bfloat16*>(w_up_gate);
    host.w_down = static_cast<const __nv_bfloat16*>(w_down);
    host.rank = rank; host.comm_ctas = comm_ctas;
    host.chunks = chunks; host.steal_budget = steal_budget;
    *result = nullptr;
    void* pointer = nullptr;
    error = cudaMalloc(&pointer, sizeof(Params));
    if (error != cudaSuccess) return int(error);
    error = cudaMemcpy(pointer, &host, sizeof(Params), cudaMemcpyHostToDevice);
    if (error != cudaSuccess) { cudaFree(pointer); return int(error); }
    *result = pointer;
    return 0;
}

extern "C" int @ENTRY@_launch(void** parameters) {
    if (!parameters) return int(cudaErrorInvalidValue);
    int count = 0;
    cudaError_t error = cudaGetDeviceCount(&count);
    if (error != cudaSuccess || count != R) return int(cudaErrorInvalidDevice);
    for (int rank = 0; rank < R; ++rank) {
        error = cudaSetDevice(rank);
        if (error != cudaSuccess) return int(error);
        cudaDeviceProp prop{};
        error = cudaGetDeviceProperties(&prop, rank);
        if (error != cudaSuccess) return int(error);
        if ((@DEVICE_NAME_CHECK@) ||
            prop.major != @MAJOR@ || prop.minor != @MINOR@ ||
            prop.multiProcessorCount != SMS) return int(cudaErrorInvalidDevice);
        int cooperative = 0;
        error = cudaDeviceGetAttribute(&cooperative, cudaDevAttrCooperativeLaunch, rank);
        if (error != cudaSuccess || cooperative != 1) return int(cudaErrorNotSupported);
        int resident = 0;
        error = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
            &resident, @ENTRY@_kernel, 32, 0);
        if (error != cudaSuccess || resident < 1) return int(cudaErrorCooperativeLaunchTooLarge);
        for (int peer = 0; peer < R; ++peer) {
            if (peer == rank) continue;
            int access = 0, native_atomic = 0;
            // CAKE_EFFECT: peer_pair.admit
            error = cudaDeviceCanAccessPeer(&access, rank, peer);
            if (error != cudaSuccess || access != 1) return int(cudaErrorNotSupported);
            error = cudaDeviceGetP2PAttribute(&native_atomic,
                cudaDevP2PAttrNativeAtomicSupported, rank, peer);
            if (error != cudaSuccess || native_atomic != 1)
                return int(cudaErrorNotSupported);
            error = cudaDeviceEnablePeerAccess(peer, 0);
            if (error != cudaSuccess && error != cudaErrorPeerAccessAlreadyEnabled)
                return int(error);
        }
    }
    for (int rank = 0; rank < R; ++rank) {
        error = cudaSetDevice(rank);
        if (error != cudaSuccess) return int(error);
        void* args[] = {&parameters[rank]};
        error = cudaLaunchCooperativeKernel(reinterpret_cast<const void*>(@ENTRY@_kernel),
            dim3(SMS), dim3(32), args, 0, nullptr);
        if (error != cudaSuccess) return int(error);
    }
    return 0;
}
