from open_cake_ir.compiler import frontend as cake

@cake.schedule(name='xcore1002-fp8-bucket16-dot-64', target='xcore1002', backend='triton', entry_point='cake_fp8_bucket16_dot_64')
def matrix(lm, a: cake.Tensor((64,64), 'fp8_e4m3'), b: cake.Tensor((64,64), 'fp8_e4m3'), out: cake.Tensor((64,64), 'fp32', mode='output')):
    compute = lm.role(execution_groups=[0,1,2,3])
    row = lm.program(a, axis=0, dimension=0, tile=16)
    col = lm.program(b, axis=1, dimension=0, tile=16)
    with compute:
        a_load = lm.load(a[row,:])
        b_load = lm.load(b[col,:])
        a_half = lm.cast(a_load, to='fp16')
        b_half = lm.cast(b_load, to='fp16')
        a_sign = lm.compare(a_half, 0.0, op="ge")
        a_neg = lm.mul(a_half, -1.0)
        a_abs = lm.select(a_sign, a_half, a_neg)
        a_lo0 = lm.compare(a_abs, 0, op="ge")
        a_hi0 = lm.compare(a_abs, 0.5, op="lt")
        a_mask0 = lm.mul(a_lo0, a_hi0)
        a_bucket0 = lm.select(a_mask0, a_half, 0.0)
        a_lo1 = lm.compare(a_abs, 0.5, op="ge")
        a_hi1 = lm.compare(a_abs, 16, op="lt")
        a_mask1 = lm.mul(a_lo1, a_hi1)
        a_bucket1 = lm.select(a_mask1, a_half, 0.0)
        a_lo2 = lm.compare(a_abs, 16, op="ge")
        a_hi2 = lm.compare(a_abs, 512, op="lt")
        a_mask2 = lm.mul(a_lo2, a_hi2)
        a_bucket2 = lm.select(a_mask2, a_half, 0.0)
        b_sign = lm.compare(b_half, 0.0, op="ge")
        b_neg = lm.mul(b_half, -1.0)
        b_abs = lm.select(b_sign, b_half, b_neg)
        b_lo0 = lm.compare(b_abs, 0, op="ge")
        b_hi0 = lm.compare(b_abs, 0.5, op="lt")
        b_mask0 = lm.mul(b_lo0, b_hi0)
        b_bucket0 = lm.select(b_mask0, b_half, 0.0)
        b_lo1 = lm.compare(b_abs, 0.5, op="ge")
        b_hi1 = lm.compare(b_abs, 16, op="lt")
        b_mask1 = lm.mul(b_lo1, b_hi1)
        b_bucket1 = lm.select(b_mask1, b_half, 0.0)
        b_lo2 = lm.compare(b_abs, 16, op="ge")
        b_hi2 = lm.compare(b_abs, 512, op="lt")
        b_mask2 = lm.mul(b_lo2, b_hi2)
        b_bucket2 = lm.select(b_mask2, b_half, 0.0)
        p0 = lm.mma(a_bucket0, b_bucket0, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p1 = lm.mma(a_bucket0, b_bucket1, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p2 = lm.mma(a_bucket0, b_bucket2, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p3 = lm.mma(a_bucket1, b_bucket0, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p4 = lm.mma(a_bucket1, b_bucket1, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p5 = lm.mma(a_bucket1, b_bucket2, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p6 = lm.mma(a_bucket2, b_bucket0, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p7 = lm.mma(a_bucket2, b_bucket1, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p8 = lm.mma(a_bucket2, b_bucket2, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        t1 = lm.add(p0, p1)
        t2 = lm.add(t1, p2)
        t3 = lm.add(t2, p3)
        t4 = lm.add(t3, p4)
        t5 = lm.add(t4, p5)
        t6 = lm.add(t5, p6)
        t7 = lm.add(t6, p7)
        t8 = lm.add(t7, p8)
        lm.store(out[row,col], t8)
