from open_cake_ir.compiler import frontend as cake

@cake.schedule(name='xcore1002-fp8-bucket16-dot-64', target='xcore1002', backend='triton', entry_point='cake_fp8_bucket16_dot_64')
def matrix(lm, a: cake.Tensor((64,64), 'fp8_e4m3'), b: cake.Tensor((64,64), 'fp8_e4m3'), out: cake.Tensor((64,64), 'fp32', mode='output')):
    compute = lm.role(execution_groups=[0,1,2,3])
    row = lm.program(a, axis=0, dimension=0, tile=16)
    col = lm.program(b, axis=1, dimension=0, tile=16)
    with compute:
        a_load = lm.load(a[row,:])
        b_load = lm.load(b[col,:])
        a_half = lm.cast(a_load, to='fp16')
        b_half = lm.cast(b_load, to='fp16')
        a_sign = lm.compare(a_half, 0.0, op="ge")
        a_neg = lm.mul(a_half, -1.0)
        a_abs = lm.select(a_sign, a_half, a_neg)
        a_lo0 = lm.compare(a_abs, 0, op="ge")
        a_hi0 = lm.compare(a_abs, 0.5, op="lt")
        a_mask0 = lm.mul(a_lo0, a_hi0)
        a_bucket0 = lm.select(a_mask0, a_half, 0.0)
        a_lo1 = lm.compare(a_abs, 0.5, op="ge")
        a_hi1 = lm.compare(a_abs, 16, op="lt")
        a_mask1 = lm.mul(a_lo1, a_hi1)
        a_bucket1 = lm.select(a_mask1, a_half, 0.0)
        a_lo2 = lm.compare(a_abs, 16, op="ge")
        a_hi2 = lm.compare(a_abs, 512, op="lt")
        a_mask2 = lm.mul(a_lo2, a_hi2)
        a_bucket2 = lm.select(a_mask2, a_half, 0.0)
        b_sign = lm.compare(b_half, 0.0, op="ge")
        b_neg = lm.mul(b_half, -1.0)
        b_abs = lm.select(b_sign, b_half, b_neg)
        b_lo0 = lm.compare(b_abs, 0, op="ge")
        b_hi0 = lm.compare(b_abs, 0.5, op="lt")
        b_mask0 = lm.mul(b_lo0, b_hi0)
        b_bucket0 = lm.select(b_mask0, b_half, 0.0)
        b_lo1 = lm.compare(b_abs, 0.5, op="ge")
        b_hi1 = lm.compare(b_abs, 16, op="lt")
        b_mask1 = lm.mul(b_lo1, b_hi1)
        b_bucket1 = lm.select(b_mask1, b_half, 0.0)
        b_lo2 = lm.compare(b_abs, 16, op="ge")
        b_hi2 = lm.compare(b_abs, 512, op="lt")
        b_mask2 = lm.mul(b_lo2, b_hi2)
        b_bucket2 = lm.select(b_mask2, b_half, 0.0)
        p0 = lm.mma(a_bucket0, b_bucket0, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p1 = lm.mma(a_bucket0, b_bucket1, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p2 = lm.mma(a_bucket0, b_bucket2, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p3 = lm.mma(a_bucket1, b_bucket0, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p4 = lm.mma(a_bucket1, b_bucket1, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p5 = lm.mma(a_bucket1, b_bucket2, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p6 = lm.mma(a_bucket2, b_bucket0, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p7 = lm.mma(a_bucket2, b_bucket1, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        p8 = lm.mma(a_bucket2, b_bucket2, instruction={"contract":"triton.dot.fp16_fp32"}, tile_shape=(16,16,64))
        c0 = lm.mul(p0, 0.0)
        t1 = lm.add(p0, p1)
        t1_abs_sign = lm.compare(p0, 0.0, op="ge")
        t1_abs_neg = lm.mul(p0, -1.0)
        t1_abs = lm.select(t1_abs_sign, p0, t1_abs_neg)
        p1_abs_sign = lm.compare(p1, 0.0, op="ge")
        p1_abs_neg = lm.mul(p1, -1.0)
        p1_abs = lm.select(p1_abs_sign, p1, p1_abs_neg)
        choose1 = lm.compare(t1_abs, p1_abs, op="ge")
        sub_a1 = lm.sub(p0, t1)
        err_a1 = lm.add(sub_a1, p1)
        sub_b1 = lm.sub(p1, t1)
        err_b1 = lm.add(sub_b1, p0)
        err1 = lm.select(choose1, err_a1, err_b1)
        c1 = lm.add(c0, err1)
        t2 = lm.add(t1, p2)
        t2_abs_sign = lm.compare(t1, 0.0, op="ge")
        t2_abs_neg = lm.mul(t1, -1.0)
        t2_abs = lm.select(t2_abs_sign, t1, t2_abs_neg)
        p2_abs_sign = lm.compare(p2, 0.0, op="ge")
        p2_abs_neg = lm.mul(p2, -1.0)
        p2_abs = lm.select(p2_abs_sign, p2, p2_abs_neg)
        choose2 = lm.compare(t2_abs, p2_abs, op="ge")
        sub_a2 = lm.sub(t1, t2)
        err_a2 = lm.add(sub_a2, p2)
        sub_b2 = lm.sub(p2, t2)
        err_b2 = lm.add(sub_b2, t1)
        err2 = lm.select(choose2, err_a2, err_b2)
        c2 = lm.add(c1, err2)
        t3 = lm.add(t2, p3)
        t3_abs_sign = lm.compare(t2, 0.0, op="ge")
        t3_abs_neg = lm.mul(t2, -1.0)
        t3_abs = lm.select(t3_abs_sign, t2, t3_abs_neg)
        p3_abs_sign = lm.compare(p3, 0.0, op="ge")
        p3_abs_neg = lm.mul(p3, -1.0)
        p3_abs = lm.select(p3_abs_sign, p3, p3_abs_neg)
        choose3 = lm.compare(t3_abs, p3_abs, op="ge")
        sub_a3 = lm.sub(t2, t3)
        err_a3 = lm.add(sub_a3, p3)
        sub_b3 = lm.sub(p3, t3)
        err_b3 = lm.add(sub_b3, t2)
        err3 = lm.select(choose3, err_a3, err_b3)
        c3 = lm.add(c2, err3)
        t4 = lm.add(t3, p4)
        t4_abs_sign = lm.compare(t3, 0.0, op="ge")
        t4_abs_neg = lm.mul(t3, -1.0)
        t4_abs = lm.select(t4_abs_sign, t3, t4_abs_neg)
        p4_abs_sign = lm.compare(p4, 0.0, op="ge")
        p4_abs_neg = lm.mul(p4, -1.0)
        p4_abs = lm.select(p4_abs_sign, p4, p4_abs_neg)
        choose4 = lm.compare(t4_abs, p4_abs, op="ge")
        sub_a4 = lm.sub(t3, t4)
        err_a4 = lm.add(sub_a4, p4)
        sub_b4 = lm.sub(p4, t4)
        err_b4 = lm.add(sub_b4, t3)
        err4 = lm.select(choose4, err_a4, err_b4)
        c4 = lm.add(c3, err4)
        t5 = lm.add(t4, p5)
        t5_abs_sign = lm.compare(t4, 0.0, op="ge")
        t5_abs_neg = lm.mul(t4, -1.0)
        t5_abs = lm.select(t5_abs_sign, t4, t5_abs_neg)
        p5_abs_sign = lm.compare(p5, 0.0, op="ge")
        p5_abs_neg = lm.mul(p5, -1.0)
        p5_abs = lm.select(p5_abs_sign, p5, p5_abs_neg)
        choose5 = lm.compare(t5_abs, p5_abs, op="ge")
        sub_a5 = lm.sub(t4, t5)
        err_a5 = lm.add(sub_a5, p5)
        sub_b5 = lm.sub(p5, t5)
        err_b5 = lm.add(sub_b5, t4)
        err5 = lm.select(choose5, err_a5, err_b5)
        c5 = lm.add(c4, err5)
        t6 = lm.add(t5, p6)
        t6_abs_sign = lm.compare(t5, 0.0, op="ge")
        t6_abs_neg = lm.mul(t5, -1.0)
        t6_abs = lm.select(t6_abs_sign, t5, t6_abs_neg)
        p6_abs_sign = lm.compare(p6, 0.0, op="ge")
        p6_abs_neg = lm.mul(p6, -1.0)
        p6_abs = lm.select(p6_abs_sign, p6, p6_abs_neg)
        choose6 = lm.compare(t6_abs, p6_abs, op="ge")
        sub_a6 = lm.sub(t5, t6)
        err_a6 = lm.add(sub_a6, p6)
        sub_b6 = lm.sub(p6, t6)
        err_b6 = lm.add(sub_b6, t5)
        err6 = lm.select(choose6, err_a6, err_b6)
        c6 = lm.add(c5, err6)
        t7 = lm.add(t6, p7)
        t7_abs_sign = lm.compare(t6, 0.0, op="ge")
        t7_abs_neg = lm.mul(t6, -1.0)
        t7_abs = lm.select(t7_abs_sign, t6, t7_abs_neg)
        p7_abs_sign = lm.compare(p7, 0.0, op="ge")
        p7_abs_neg = lm.mul(p7, -1.0)
        p7_abs = lm.select(p7_abs_sign, p7, p7_abs_neg)
        choose7 = lm.compare(t7_abs, p7_abs, op="ge")
        sub_a7 = lm.sub(t6, t7)
        err_a7 = lm.add(sub_a7, p7)
        sub_b7 = lm.sub(p7, t7)
        err_b7 = lm.add(sub_b7, t6)
        err7 = lm.select(choose7, err_a7, err_b7)
        c7 = lm.add(c6, err7)
        t8 = lm.add(t7, p8)
        t8_abs_sign = lm.compare(t7, 0.0, op="ge")
        t8_abs_neg = lm.mul(t7, -1.0)
        t8_abs = lm.select(t8_abs_sign, t7, t8_abs_neg)
        p8_abs_sign = lm.compare(p8, 0.0, op="ge")
        p8_abs_neg = lm.mul(p8, -1.0)
        p8_abs = lm.select(p8_abs_sign, p8, p8_abs_neg)
        choose8 = lm.compare(t8_abs, p8_abs, op="ge")
        sub_a8 = lm.sub(t7, t8)
        err_a8 = lm.add(sub_a8, p8)
        sub_b8 = lm.sub(p8, t8)
        err_b8 = lm.add(sub_b8, t7)
        err8 = lm.select(choose8, err_a8, err_b8)
        c8 = lm.add(c7, err8)
        result = lm.add(t8, c8)
        lm.store(out[row,col], result)
