"""Semantic capture metadata only; no upstream candidate or timing is imported."""

SPECS = {'fib_gqa_paged_decode_h32_kv4_d128_ps1': {'upstream': '012_gqa_paged_decode_h32_kv4_d128_ps1',
                                           'family': 'gqa_paged',
                                           'decode': True,
                                           'mla': False,
                                           'paged': True,
                                           'constants': {'num_qo_heads': 32,
                                                         'num_kv_heads': 4,
                                                         'head_dim': 128,
                                                         'page_size': 1},
                                           'captured_axes': {'batch_size': 1,
                                                             'num_pages': 8,
                                                             'len_indptr': 2,
                                                             'num_kv_indices': 7},
                                           'captured_scale': 0.0883883461356163,
                                           'workload_uuid': '0c2489b2-f878-428b-b1bd-d0c6d4c39338',
                                           'inputs': {'q': {'shape': ['batch_size',
                                                                      'num_qo_heads',
                                                                      'head_dim'],
                                                            'dtype': 'bf16'},
                                                      'k_cache': {'shape': ['num_pages',
                                                                            'page_size',
                                                                            'num_kv_heads',
                                                                            'head_dim'],
                                                                  'dtype': 'bf16'},
                                                      'v_cache': {'shape': ['num_pages',
                                                                            'page_size',
                                                                            'num_kv_heads',
                                                                            'head_dim'],
                                                                  'dtype': 'bf16'},
                                                      'kv_indptr': {'shape': ['len_indptr'],
                                                                    'dtype': 'int32'},
                                                      'kv_indices': {'shape': ['num_kv_indices'],
                                                                     'dtype': 'int32'},
                                                      'sm_scale': {'shape': [1], 'dtype': 'fp32'}},
                                           'outputs': {'output': {'shape': ['batch_size',
                                                                            'num_qo_heads',
                                                                            'head_dim'],
                                                                  'dtype': 'bf16'},
                                                       'lse': {'shape': ['batch_size',
                                                                         'num_qo_heads'],
                                                               'dtype': 'fp32'}}},
 'fib_gqa_paged_decode_h32_kv8_d128_ps1': {'upstream': '013_gqa_paged_decode_h32_kv8_d128_ps1',
                                           'family': 'gqa_paged',
                                           'decode': True,
                                           'mla': False,
                                           'paged': True,
                                           'constants': {'num_qo_heads': 32,
                                                         'num_kv_heads': 8,
                                                         'head_dim': 128,
                                                         'page_size': 1},
                                           'captured_axes': {'batch_size': 1,
                                                             'num_pages': 9316,
                                                             'len_indptr': 2,
                                                             'num_kv_indices': 73},
                                           'captured_scale': 0.08838834764831843,
                                           'workload_uuid': 'e2142798-a0ce-49dd-9eaa-72727ad69f0f',
                                           'inputs': {'q': {'shape': ['batch_size',
                                                                      'num_qo_heads',
                                                                      'head_dim'],
                                                            'dtype': 'bf16'},
                                                      'k_cache': {'shape': ['num_pages',
                                                                            'page_size',
                                                                            'num_kv_heads',
                                                                            'head_dim'],
                                                                  'dtype': 'bf16'},
                                                      'v_cache': {'shape': ['num_pages',
                                                                            'page_size',
                                                                            'num_kv_heads',
                                                                            'head_dim'],
                                                                  'dtype': 'bf16'},
                                                      'kv_indptr': {'shape': ['len_indptr'],
                                                                    'dtype': 'int32'},
                                                      'kv_indices': {'shape': ['num_kv_indices'],
                                                                     'dtype': 'int32'},
                                                      'sm_scale': {'shape': [1], 'dtype': 'fp32'}},
                                           'outputs': {'output': {'shape': ['batch_size',
                                                                            'num_qo_heads',
                                                                            'head_dim'],
                                                                  'dtype': 'bf16'},
                                                       'lse': {'shape': ['batch_size',
                                                                         'num_qo_heads'],
                                                               'dtype': 'fp32'}}},
 'fib_gqa_paged_prefill_causal_h32_kv4_d128_ps1': {'upstream': '014_gqa_paged_prefill_causal_h32_kv4_d128_ps1',
                                                   'family': 'gqa_paged',
                                                   'decode': False,
                                                   'mla': False,
                                                   'paged': True,
                                                   'constants': {'num_qo_heads': 32,
                                                                 'num_kv_heads': 4,
                                                                 'head_dim': 128,
                                                                 'page_size': 1},
                                                   'captured_axes': {'len_indptr': 2,
                                                                     'total_q': 1,
                                                                     'num_kv_indices': 33,
                                                                     'num_pages': 50},
                                                   'captured_scale': 0.08838834764831843,
                                                   'workload_uuid': 'c3c5535c-1829-4618-b629-129c0190dfc4',
                                                   'inputs': {'q': {'shape': ['total_q',
                                                                              'num_qo_heads',
                                                                              'head_dim'],
                                                                    'dtype': 'bf16'},
                                                              'k_cache': {'shape': ['num_pages',
                                                                                    'page_size',
                                                                                    'num_kv_heads',
                                                                                    'head_dim'],
                                                                          'dtype': 'bf16'},
                                                              'v_cache': {'shape': ['num_pages',
                                                                                    'page_size',
                                                                                    'num_kv_heads',
                                                                                    'head_dim'],
                                                                          'dtype': 'bf16'},
                                                              'qo_indptr': {'shape': ['len_indptr'],
                                                                            'dtype': 'int32'},
                                                              'kv_indptr': {'shape': ['len_indptr'],
                                                                            'dtype': 'int32'},
                                                              'kv_indices': {'shape': ['num_kv_indices'],
                                                                             'dtype': 'int32'},
                                                              'sm_scale': {'shape': [1],
                                                                           'dtype': 'fp32'}},
                                                   'outputs': {'output': {'shape': ['total_q',
                                                                                    'num_qo_heads',
                                                                                    'head_dim'],
                                                                          'dtype': 'bf16'},
                                                               'lse': {'shape': ['total_q',
                                                                                 'num_qo_heads'],
                                                                       'dtype': 'fp32'}}},
 'fib_gqa_paged_prefill_causal_h32_kv8_d128_ps1': {'upstream': '015_gqa_paged_prefill_causal_h32_kv8_d128_ps1',
                                                   'family': 'gqa_paged',
                                                   'decode': False,
                                                   'mla': False,
                                                   'paged': True,
                                                   'constants': {'num_qo_heads': 32,
                                                                 'num_kv_heads': 8,
                                                                 'head_dim': 128,
                                                                 'page_size': 1},
                                                   'captured_axes': {'len_indptr': 2,
                                                                     'total_q': 34,
                                                                     'num_kv_indices': 1,
                                                                     'num_pages': 2},
                                                   'captured_scale': 0.08838834764831843,
                                                   'workload_uuid': 'fc772d69-9b89-4dd5-b125-76b9cc673c85',
                                                   'inputs': {'q': {'shape': ['total_q',
                                                                              'num_qo_heads',
                                                                              'head_dim'],
                                                                    'dtype': 'bf16'},
                                                              'k_cache': {'shape': ['num_pages',
                                                                                    'page_size',
                                                                                    'num_kv_heads',
                                                                                    'head_dim'],
                                                                          'dtype': 'bf16'},
                                                              'v_cache': {'shape': ['num_pages',
                                                                                    'page_size',
                                                                                    'num_kv_heads',
                                                                                    'head_dim'],
                                                                          'dtype': 'bf16'},
                                                              'qo_indptr': {'shape': ['len_indptr'],
                                                                            'dtype': 'int32'},
                                                              'kv_indptr': {'shape': ['len_indptr'],
                                                                            'dtype': 'int32'},
                                                              'kv_indices': {'shape': ['num_kv_indices'],
                                                                             'dtype': 'int32'},
                                                              'sm_scale': {'shape': [1],
                                                                           'dtype': 'fp32'}},
                                                   'outputs': {'output': {'shape': ['total_q',
                                                                                    'num_qo_heads',
                                                                                    'head_dim'],
                                                                          'dtype': 'bf16'},
                                                               'lse': {'shape': ['total_q',
                                                                                 'num_qo_heads'],
                                                                       'dtype': 'fp32'}}},
 'fib_gqa_ragged_prefill_causal_h32_kv4_d128': {'upstream': '016_gqa_ragged_prefill_causal_h32_kv4_d128',
                                                'family': 'gqa_ragged',
                                                'decode': False,
                                                'mla': False,
                                                'paged': False,
                                                'constants': {'num_qo_heads': 32,
                                                              'num_kv_heads': 4,
                                                              'head_dim': 128},
                                                'captured_axes': {'len_indptr': 2,
                                                                  'total_q': 6,
                                                                  'total_kv': 6},
                                                'captured_scale': 0.0883883461356163,
                                                'workload_uuid': 'ebf7188b-4b31-4746-b57b-fa25b53f5e3e',
                                                'inputs': {'q': {'shape': ['total_q',
                                                                           'num_qo_heads',
                                                                           'head_dim'],
                                                                 'dtype': 'bf16'},
                                                           'k': {'shape': ['total_kv',
                                                                           'num_kv_heads',
                                                                           'head_dim'],
                                                                 'dtype': 'bf16'},
                                                           'v': {'shape': ['total_kv',
                                                                           'num_kv_heads',
                                                                           'head_dim'],
                                                                 'dtype': 'bf16'},
                                                           'qo_indptr': {'shape': ['len_indptr'],
                                                                         'dtype': 'int32'},
                                                           'kv_indptr': {'shape': ['len_indptr'],
                                                                         'dtype': 'int32'},
                                                           'sm_scale': {'shape': [1],
                                                                        'dtype': 'fp32'}},
                                                'outputs': {'output': {'shape': ['total_q',
                                                                                 'num_qo_heads',
                                                                                 'head_dim'],
                                                                       'dtype': 'bf16'},
                                                            'lse': {'shape': ['total_q',
                                                                              'num_qo_heads'],
                                                                    'dtype': 'fp32'}}},
 'fib_gqa_ragged_prefill_causal_h32_kv8_d128': {'upstream': '017_gqa_ragged_prefill_causal_h32_kv8_d128',
                                                'family': 'gqa_ragged',
                                                'decode': False,
                                                'mla': False,
                                                'paged': False,
                                                'constants': {'num_qo_heads': 32,
                                                              'num_kv_heads': 8,
                                                              'head_dim': 128},
                                                'captured_axes': {'len_indptr': 2,
                                                                  'total_q': 7,
                                                                  'total_kv': 7},
                                                'captured_scale': 0.0883883461356163,
                                                'workload_uuid': 'f7a038e9-6c18-4fd6-9b79-e349a4c79bd8',
                                                'inputs': {'q': {'shape': ['total_q',
                                                                           'num_qo_heads',
                                                                           'head_dim'],
                                                                 'dtype': 'bf16'},
                                                           'k': {'shape': ['total_kv',
                                                                           'num_kv_heads',
                                                                           'head_dim'],
                                                                 'dtype': 'bf16'},
                                                           'v': {'shape': ['total_kv',
                                                                           'num_kv_heads',
                                                                           'head_dim'],
                                                                 'dtype': 'bf16'},
                                                           'qo_indptr': {'shape': ['len_indptr'],
                                                                         'dtype': 'int32'},
                                                           'kv_indptr': {'shape': ['len_indptr'],
                                                                         'dtype': 'int32'},
                                                           'sm_scale': {'shape': [1],
                                                                        'dtype': 'fp32'}},
                                                'outputs': {'output': {'shape': ['total_q',
                                                                                 'num_qo_heads',
                                                                                 'head_dim'],
                                                                       'dtype': 'bf16'},
                                                            'lse': {'shape': ['total_q',
                                                                              'num_qo_heads'],
                                                                    'dtype': 'fp32'}}},
 'fib_mla_paged_decode_h16_ckv512_kpe64_ps1': {'upstream': '018_mla_paged_decode_h16_ckv512_kpe64_ps1',
                                               'family': 'mla_paged',
                                               'decode': True,
                                               'mla': True,
                                               'paged': True,
                                               'constants': {'num_qo_heads': 16,
                                                             'head_dim_ckv': 512,
                                                             'head_dim_kpe': 64,
                                                             'page_size': 1},
                                               'captured_axes': {'batch_size': 1,
                                                                 'num_pages': 989669,
                                                                 'len_indptr': 2,
                                                                 'num_kv_indices': 8},
                                               'captured_scale': 0.1352337747812271,
                                               'workload_uuid': '00cb2bc2-c7c7-43a1-b857-b516eb2ce061',
                                               'inputs': {'q_nope': {'shape': ['batch_size',
                                                                               'num_qo_heads',
                                                                               'head_dim_ckv'],
                                                                     'dtype': 'bf16'},
                                                          'q_pe': {'shape': ['batch_size',
                                                                             'num_qo_heads',
                                                                             'head_dim_kpe'],
                                                                   'dtype': 'bf16'},
                                                          'ckv_cache': {'shape': ['num_pages',
                                                                                  'page_size',
                                                                                  'head_dim_ckv'],
                                                                        'dtype': 'bf16'},
                                                          'kpe_cache': {'shape': ['num_pages',
                                                                                  'page_size',
                                                                                  'head_dim_kpe'],
                                                                        'dtype': 'bf16'},
                                                          'kv_indptr': {'shape': ['len_indptr'],
                                                                        'dtype': 'int32'},
                                                          'kv_indices': {'shape': ['num_kv_indices'],
                                                                         'dtype': 'int32'},
                                                          'sm_scale': {'shape': [1],
                                                                       'dtype': 'fp32'}},
                                               'outputs': {'output': {'shape': ['batch_size',
                                                                                'num_qo_heads',
                                                                                'head_dim_ckv'],
                                                                      'dtype': 'bf16'},
                                                           'lse': {'shape': ['batch_size',
                                                                             'num_qo_heads'],
                                                                   'dtype': 'fp32'}}},
 'fib_mla_paged_prefill_causal_h16_ckv512_kpe64_ps1': {'upstream': '019_mla_paged_prefill_causal_h16_ckv512_kpe64_ps1',
                                                       'family': 'mla_paged',
                                                       'decode': False,
                                                       'mla': True,
                                                       'paged': True,
                                                       'constants': {'num_qo_heads': 16,
                                                                     'head_dim_ckv': 512,
                                                                     'head_dim_kpe': 64,
                                                                     'page_size': 1},
                                                       'captured_axes': {'total_q': 33,
                                                                         'num_pages': 989669,
                                                                         'len_indptr': 2,
                                                                         'num_kv_indices': 34},
                                                       'captured_scale': 0.1352337747812271,
                                                       'workload_uuid': '55b51e96-eecc-4dc9-814a-0f1301b2951e',
                                                       'inputs': {'q_nope': {'shape': ['total_q',
                                                                                       'num_qo_heads',
                                                                                       'head_dim_ckv'],
                                                                             'dtype': 'bf16'},
                                                                  'q_pe': {'shape': ['total_q',
                                                                                     'num_qo_heads',
                                                                                     'head_dim_kpe'],
                                                                           'dtype': 'bf16'},
                                                                  'ckv_cache': {'shape': ['num_pages',
                                                                                          'page_size',
                                                                                          'head_dim_ckv'],
                                                                                'dtype': 'bf16'},
                                                                  'kpe_cache': {'shape': ['num_pages',
                                                                                          'page_size',
                                                                                          'head_dim_kpe'],
                                                                                'dtype': 'bf16'},
                                                                  'qo_indptr': {'shape': ['len_indptr'],
                                                                                'dtype': 'int32'},
                                                                  'kv_indptr': {'shape': ['len_indptr'],
                                                                                'dtype': 'int32'},
                                                                  'kv_indices': {'shape': ['num_kv_indices'],
                                                                                 'dtype': 'int32'},
                                                                  'sm_scale': {'shape': [1],
                                                                               'dtype': 'fp32'}},
                                                       'outputs': {'output': {'shape': ['total_q',
                                                                                        'num_qo_heads',
                                                                                        'head_dim_ckv'],
                                                                              'dtype': 'bf16'},
                                                                   'lse': {'shape': ['total_q',
                                                                                     'num_qo_heads'],
                                                                           'dtype': 'fp32'}}}}
