#!/usr/bin/env python3
"""Render the DCU results report from the retained medians.

The report this writes was a hand-written file outside the repository for two days, and it
kept an argument F-2026-09-18-002 has since withdrawn -- the floor argued from bytes -- plus
a task count the ledger had already corrected twice. A reader with the report and no ledger
would have believed all of it.

So the report is generated. Every count, median, ratio and curve point comes from
`findings/data/2026-09-18-dcu-confirmatory-medians.json`; the prose around them is here, in
one place, where it can be reviewed beside the numbers it frames. Re-running this after the
table changes is what keeps the two from drifting, and `--check` fails if they have.

This renders. It measures nothing, reaches no device, and is not evidence: the records under
`findings/` are, and where the report disagrees with one, the record wins.

    python3 tools/render_dcu_report.py --write
    python3 tools/render_dcu_report.py --check    # non-zero if the committed file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "findings/data/2026-09-18-dcu-confirmatory-medians.json"
REPORT = ROOT / "docs/dcu-gfx938-results.md"

#: Facts the Target declares with a device measurement behind each. These are not in the
#: medians table -- they are its `instruction_contracts` citations, restated for a reader.
DECLARED = (
    ("`warp_size: 64`", "rocminfo, hipGetDeviceProperties"),
    ("operation kind `mma`", "`v_mmac_f32_16x16x16_f16`, `v_mmac_f32_16x16x32_fp8_fp8`"),
    ("`triton.dot.fp16_fp32`", "64³ vs torch oracle, max_abs_error 1.14e-05"),
    ("`triton.dot.fp8e4m3_fp32`", "64³ vs torch oracle, max_abs_error 0"),
    ("`triton.dot.fp32_ieee`", "`v_mmac_16x16x8_f32`, max_abs_error 0"),
    ("`triton.dot.fp32_tf32`", "`v_mmac_f32_16x16x8_tf32`, rel 7.18e-04"),
    ("`ocml.tanh.f32`", "`__ocml_tanh_f32`, max rel 1.07e-07 across the saturating tails"),
)


def render(data: dict) -> str:
    rows, floor = data["medians_ms"], data["floor_ms"]
    ratio = data["materiality_ratio"]
    quantum = data["timer_quantum_ns"]
    sweep = data["footprint_sweep"]
    curve = {row["mib_moved"]: row["median_us"] for row in sweep["per_size"]}

    at = sorted(t for t, r in rows.items()
                if r["candidate"] == floor and r["baseline"] == floor)
    ahead = {t: round(r["baseline"] / r["candidate"], 3)
             for t, r in rows.items() if r["baseline"] > r["candidate"]}
    material = {t: v for t, v in ahead.items() if v > ratio}
    inside = {t: v for t, v in ahead.items() if t not in material}
    behind = {t: round(r["baseline"] / r["candidate"], 3)
              for t, r in rows.items() if r["baseline"] < r["candidate"]}
    distinct = {r[k] for r in rows.values() for k in ("candidate", "baseline")}

    def rows_for(pairs):
        return "\n".join(
            f"| `{t}` | {rows[t]['candidate']:.6f} | {rows[t]['baseline']:.6f} | {v:.3f} |"
            for t, v in sorted(pairs.items(), key=lambda kv: -kv[1]))

    # How many quanta apart the two sizes the proposed shape change turns on are.
    span = round((curve[8.0] - curve[1.0]) * 1000 / quantum)
    step_lo, step_hi = 0.5, 2.0
    one_step = all(round((curve[size + step_lo] - curve[size]) * 1000) == quantum
                   for size in curve if step_lo <= size < step_hi and size + step_lo in curve)

    return f"""# open-cake-ir on Hygon DCU (gfx938 / {sweep['device']})

Campaigns of 2026-09-17 and 2026-09-18, model `deepseek-v4-flash` through an
Anthropic-compatible endpoint.

Every figure below is candidate against fixed baseline **inside one task**, case, target
and assay, under claim scope `artifact_optimization_only`. It is not an arm comparison and
not a speedup against any external reference. The baseline is the starter reference each
task ships with.

*Generated by `tools/render_dcu_report.py` from
`findings/data/2026-09-18-dcu-confirmatory-medians.json`. This is a reading of the findings
ledger, not a second source: where it disagrees with a record under `findings/`, the record
wins. It is generated because the hand-written draft it replaces lived outside the
repository for two days and kept an argument F-2026-09-18-002 had already withdrawn.*

## Coverage

**{len(rows)} of 29 tasks reached a qualified endpoint.** The gate was turn budget, not
capability (F-2026-09-18-003):

| turns / token budget | tasks qualified |
|---|---|
| 2 / 200k | 21 |
| 4 / 400k | 25 |
| 6 / 600k | **{len(rows)}** |

Each distinct verifier refusal costs one turn to recover from, so a task that trips several
needs enough turns to absorb them. `softmax` drew five *different* refusals across four
runs and still converged at six.

Two tasks never qualify, for reasons outside that axis:

- `gemm_bias` — blocked on every target. Its `mixed_magnitude` tolerance is met by no fp32
  accumulation order; only fp64 accumulation lands inside it (F-2026-09-18-004).
- `gemm_silu` — the baseline passes all five validation cases and the candidate fails all
  five, by 0.5 to 100.8. A wrong kernel caught by the oracle: the harness working.

So of the 28 tasks that *can* qualify, {len(rows)} do.

## Candidates that beat their baseline

Declared materiality ratio {ratio}; these clear it (F-2026-09-18-005):

| task | candidate ms | baseline ms | ratio |
|---|---|---|---|
{rows_for(material)}

{len(inside)} more are nominally ahead and inside materiality — """ + " and ".join(
        f"`{t}` at {v:.3f}" for t, v in sorted(inside.items())) + f""" — so
{len(ahead)} are ahead and {len(material)} by enough to say so. One further run,
`gelu_tanh`'s discarded second campaign, clears materiality with its candidate sitting
exactly on the floor below, and is excluded for that reason rather than counted.

## Candidates that lost

| task | candidate ms | baseline ms | ratio |
|---|---|---|---|
{rows_for(behind)}

## The measurement floor — read the rest with care

**{len(at)} tasks report exactly {floor} ms for both arms.** The reason is the timer, not
the kernels: every one of the {len(distinct)} distinct medians in this collection is an
exact multiple of **{quantum} ns**, offset by a constant. The footprint probe reports the
same grid independently as its `resolution_us`.

The curve, measured on the device by `tools/probe_dcu_shape_floor.py`:

| MiB moved | median us | GB/s |
|---|---|---|
""" + "\n".join(f"| {r['mib_moved']:.2f} | {r['median_us']:.3f} | "
                f"{r['gbytes_per_second']:.0f} |" for r in sweep["per_size"]) + f"""

From {step_lo} to {step_hi} MiB each additional {step_lo} MiB costs exactly one {quantum} ns
quantum{'' if one_step else ' (no longer true of this curve — recheck the text)'}. The task
shapes sit at 1.0–1.5 MiB, so the byte-dependent part of their cost is about **one grid
step** — and a paired comparison between two arms that both land on the same step cannot
resolve it. `close_null` for those {len(at)} is the assay saying it could not tell, which is
a different statement from the arms matching.

> An earlier version of this report argued the floor from bytes: that `silu` moves 1.000
> MiB and `softmax_backward` 1.500 while both read {floor} ms, and bandwidth-bound work
> cannot do that. **That argument is withdrawn.** The sweep predicts those two differ by
> exactly one quantum, and two readings one step apart landing in the same bucket is what a
> quantized timer does. It also said the task shapes "sit in the flat region"; at 1.0–1.5
> MiB they sit on the slope. See F-2026-09-18-002.

What remains unexplained is why these kernels cost {floor * 1000:.3f} us where the synthetic
copy kernel reads {curve[1.0]:.3f} us at the same footprint.

## What the target declares

Each fact with a device measurement in its citation:

| fact | evidence |
|---|---|
""" + "\n".join(f"| {fact} | {evidence} |" for fact, evidence in DECLARED) + f"""

Note the ISA spells its matrix instruction `v_mmac`, not AMD's `v_mfma`, and its math
library is **ocml**, not CUDA's libdevice. A probe using AMD's spellings reported that
gfx938 had no matrix instructions at all — a confident wrong answer, caught only because a
control was run beside it.

## Known open

- **F-2026-09-17-011** — with the fp32 contracts declared and Corpus-covered, `gemm` still
  lowers a contraction reaching for no matrix instruction, at the same latency to six
  decimals. The authoring environment is the only explanation still standing.
- **F-2026-09-17-010** — two models invoke `Bash`, a tool the CLI denies; the harness
  discards the whole turn although nothing ran. Concentrated per task rather than uniform.
- **F-2026-09-18-002** — the shape sweep the floor argues for has not been run as
  campaigns. The curve above says where to run it: 1.0 and 1.5 MiB are one quantum apart,
  while 1.0 and 8.0 MiB are {span}.
"""


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the report")
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed report is not what this renders")
    arguments = parser.parse_args(argv)

    rendered = render(json.loads(DATA.read_text(encoding="utf-8")))
    if arguments.check:
        current = REPORT.read_text(encoding="utf-8") if REPORT.exists() else ""
        if current != rendered:
            print(f"{REPORT.relative_to(ROOT)} is stale; re-run with --write",
                  file=sys.stderr)
            return 1
        print(f"{REPORT.relative_to(ROOT)} matches the table")
        return 0
    if arguments.write:
        REPORT.write_text(rendered, encoding="utf-8")
        print(f"wrote {REPORT.relative_to(ROOT)}")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
