#!/usr/bin/env python3
"""Render the human-readable current release view from canonical authorities."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reports" / "current" / "STATUS.md"


def _load(relative_path: str) -> dict:
    value = json.loads((ROOT / relative_path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{relative_path} must contain one JSON object")
    return value


def render() -> str:
    compiler = _load("compiler/revision.lock.json")
    executors = _load("inventory/EXECUTOR_REVISIONS.json")
    current_executor = executors.get("current")
    if not isinstance(current_executor, dict):
        raise ValueError("inventory/EXECUTOR_REVISIONS.json has no current executor")

    executor_path = current_executor.get("path")
    if not isinstance(executor_path, str):
        raise ValueError("current executor path is missing")
    executor = _load(executor_path)

    executor_id = current_executor.get("executor_id")
    if executor.get("executor_id") != executor_id:
        raise ValueError("current executor index and descriptor disagree")
    if len(executor.get("sources", [])) != current_executor.get("source_count"):
        raise ValueError("current executor source count disagrees with its descriptor")

    gate = compiler.get("corpus_gate", {})
    targets = ", ".join(sorted(compiler.get("target_definitions", {}))) or "none"
    calibration = compiler.get("calibration_coverage", [])
    calibration_text = ", ".join(calibration) if calibration else "none released"

    return "\n".join(
        [
            "# Current released authorities",
            "",
            "<!-- Generated by tools/render_current_status.py. Do not edit by hand. -->",
            "",
            "This view is derived from canonical release authorities. It reports no experimental",
            "performance claim and does not authorize a Campaign.",
            "",
            "## Compiler",
            "",
            f"- Revision: `{compiler['revision_id']}`",
            f"- State: `{compiler['state']}`",
            f"- Targets: `{targets}`",
            f"- Corpus Gate: `{gate.get('matched_case_count')}/{gate.get('case_count')}` cases matched",
            f"- Released source closure: `{len(compiler.get('sources', []))}` files",
            f"- Calibration coverage: `{calibration_text}`",
            "- Authority: [`compiler/revision.lock.json`](../../compiler/revision.lock.json)",
            "",
            "## Executor",
            "",
            f"- Revision: `{executor_id}`",
            f"- State: `{executor['state']}`",
            f"- Released source closure: `{len(executor.get('sources', []))}` files",
            "- Authority: [`inventory/EXECUTOR_REVISIONS.json`](../../inventory/EXECUTOR_REVISIONS.json)",
            f"- Descriptor: [`{executor_path}`](../../{executor_path})",
            "",
            "## Claim boundary",
            "",
            "The repository does not yet have one accepted Study Report index from which to",
            "derive a repository-wide Claim View. Operator, Program, model, and serving claims",
            "therefore remain in their bound Study Reports and Evidence; they are deliberately",
            "not copied into this release-status view.",
            "",
            "The former [`inventory/CURRENT_STATE.md`](../../inventory/CURRENT_STATE.md) is a",
            "frozen 2026-08-25 migration snapshot, not a current authority.",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render()

    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated status: {OUTPUT.relative_to(ROOT)}")
            return 1
        return 0
    if arguments.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
