#!/usr/bin/env python3
"""Render the human-readable current release view from canonical authorities."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reports" / "current" / "STATUS.md"


def _load(relative_path: str) -> dict:
    value = json.loads((ROOT / relative_path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{relative_path} must contain one JSON object")
    return value


def render() -> str:
    compiler = _load("compiler/revision.lock.json")
    executors = _load("inventory/EXECUTOR_REVISIONS.json")
    current_executor = executors.get("current")
    if not isinstance(current_executor, dict):
        raise ValueError("inventory/EXECUTOR_REVISIONS.json has no current executor")

    executor_path = current_executor.get("path")
    if not isinstance(executor_path, str):
        raise ValueError("current executor path is missing")
    executor = _load(executor_path)

    executor_id = current_executor.get("executor_id")
    if executor.get("executor_id") != executor_id:
        raise ValueError("current executor index and descriptor disagree")
    if len(executor.get("sources", [])) != current_executor.get("source_count"):
        raise ValueError("current executor source count disagrees with its descriptor")

    gate = compiler.get("corpus_gate", {})
    targets = ", ".join(sorted(compiler.get("target_definitions", {}))) or "none"
    calibration = compiler.get("calibration_coverage", [])
    calibration_text = ", ".join(calibration) if calibration else "无"

    return "\n".join(
        [
            "# 当前发布状态",
            "",
            "<!-- Generated by tools/render_current_status.py. Do not edit by hand. -->",
            "",
            "本页由发布记录自动生成，说明现在固定使用哪些版本。",
            "发布完成不代表新的 GPU 实验、性能结果或运行授权。",
            "",
            "## Compiler",
            "",
            f"- 版本： `{compiler['revision_id']}`",
            f"- 状态： `{compiler['state']}`",
            f"- 目标： `{targets}`",
            f"- 语料检查： `{gate.get('matched_case_count')}/{gate.get('case_count')}` 项符合预期",
            f"- 绑定源码： `{len(compiler.get('sources', []))}` 个文件",
            f"- 已发布校准： `{calibration_text}`",
            "- 负责记录： [`compiler/revision.lock.json`](../../compiler/revision.lock.json)",
            "",
            "## Executor",
            "",
            f"- 版本： `{executor_id}`",
            f"- 状态： `{executor['state']}`",
            f"- 绑定源码： `{len(executor.get('sources', []))}` 个文件",
            "- 负责记录： [`inventory/EXECUTOR_REVISIONS.json`](../../inventory/EXECUTOR_REVISIONS.json)",
            f"- 描述文件： [`{executor_path}`](../../{executor_path})",
            "",
            "## 这些数字说明什么",
            "",
            "项目尚无统一的已验收 Study Report 索引，不能从这些版本号生成全项目的成绩榜。",
            "算子、完整 Program、模型和服务的结果，仍以各自绑定的实验报告与原始证据为准。",
            "本页不复制这些实验结论。",
            "",
            "[`inventory/CURRENT_STATE.md`](../../inventory/CURRENT_STATE.md) 是旧迁移记录，",
            "不是当前状态；需要了解概念可从 [中文 Wiki](../../docs/wiki/README.md) 开始。",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render()

    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated status: {OUTPUT.relative_to(ROOT)}")
            return 1
        return 0
    if arguments.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
