#!/usr/bin/env python3
"""Render the human-readable current view from the Compiler manifest and host captures."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reports" / "current" / "STATUS.md"
sys.path.insert(0, str(ROOT / "src"))

from open_cake_ir.compiler import Compiler  # noqa: E402
from open_cake_ir.compiler.corpus import CorpusGateReport  # noqa: E402


def _coverage_lines(report: CorpusGateReport) -> list[str]:
    """State which Targets the pass count covers, next to that count.

    A reader who sees every declared Target listed above a passing count assumes the
    count covers all of them. Absence is reported, never repaired by minting cases.
    """

    examined = "、".join(
        f"`{target}`（{count}）" for target, count in sorted(report.examined_targets.items())
    ) or "无"
    undeclared = "、".join(
        f"`{target}`（{count}）" for target, count in sorted(report.undeclared_case_targets.items())
    ) or "无"
    unexamined = ", ".join(report.unexamined_targets)
    return [
        f"- 语料覆盖： 检查了 {examined}",
        (f"- 未检查的已声明目标： `{unexamined}`（上面的通过数不涵盖这些目标）"
         if report.unexamined_targets else "- 未检查的已声明目标： 无"),
        f"- 只用于拒绝检查的未声明目标： {undeclared}",
    ]


def _host_lines() -> list[str]:
    """One committed capture per target; a target without one has no runnable host."""

    directory = ROOT / "runtime/hosts"
    captures = sorted(directory.glob("*.json")) if directory.is_dir() else []
    if not captures:
        return ["还没有任何目标提交主机采集。", ""]
    lines: list[str] = []
    for path in captures:
        document = json.loads(path.read_text(encoding="utf-8"))
        host = document["host_environment"]
        python = host["python"]
        relative = path.relative_to(ROOT).as_posix()
        lines.extend([
            f"### `{document['target']}`",
            "",
            f"- 主机类型： `{host.get('kind') or 'cuda'}`",
            f"- 解释器： `{python['invocation_path']}`（{python['version']}）",
            f"- 采集文件： [`{relative}`](../../{relative})",
            "",
        ])
    return lines


def render() -> str:
    compiler = Compiler.load(ROOT, ROOT / "compiler/revision.json")
    report = compiler.check_corpus()
    revision = json.loads((ROOT / "compiler/revision.json").read_text(encoding="utf-8"))
    calibration = revision.get("calibration_coverage", [])
    targets = ", ".join(sorted(report.declared_targets)) or "none"
    matched = sum(case.matched for case in report.cases)

    return "\n".join(
        [
            "# 当前状态",
            "",
            "<!-- Generated by tools/render_current_status.py. Do not edit by hand. -->",
            "",
            "本页由当前提交上的编译器清单和主机采集自动生成。",
            "源码身份是这份检出的 git 提交；检查通过不代表新的 GPU 实验、性能结果或运行授权。",
            "",
            "## Compiler",
            "",
            f"- 声明的目标： `{targets}`",
            f"- 语料检查： `{matched}/{report.case_count}` 项符合预期",
            *_coverage_lines(report),
            f"- 已发布校准： `{', '.join(calibration) if calibration else '无'}`",
            "- 负责记录： [`compiler/revision.json`](../../compiler/revision.json) 与 "
            "[`compiler/targets/`](../../compiler/targets)",
            "",
            "## 主机采集（按精确目标）",
            "",
            *_host_lines(),
            "- 负责记录： [`runtime/hosts/`](../../runtime/hosts)",
            "",
            "## 这些数字说明什么",
            "",
            "项目尚无统一的已验收 Study Report 索引，不能从这一页生成全项目的成绩榜。",
            "算子、完整 Program、模型和服务的结果，仍以各自绑定的实验报告与原始证据为准。",
            "本页不复制这些实验结论。",
            "",
            "历史发布记录保留在 [`compiler/releases/`](../../compiler/releases)、",
            "[`runtime/executors/`](../../runtime/executors) 和 [`inventory/`](../../inventory)，",
            "它们只在各自的原提交上用当时的工具重放。",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render()

    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print(f"stale generated status: {OUTPUT.relative_to(ROOT)}")
            return 1
        return 0
    if arguments.write:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(rendered, encoding="utf-8")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
